import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const anchorTypesPath = path.resolve(__dirname, "../../../anchor/target/types/lili_anchor_program.ts");
const outputDir = path.resolve(__dirname, "generated");
const outputTypesPath = path.join(outputDir, "lili_anchor_program.ts");
const outputIndexPath = path.join(outputDir, "index.ts");

async function ensureGeneratedFiles() {
  await fs.mkdir(outputDir, { recursive: true });

  let typeSource: string;
  try {
    typeSource = await fs.readFile(anchorTypesPath, "utf8");
  } catch (error) {
    typeSource = "export type LiliAnchorProgram = Record<string, unknown>;\nexport const IDL: LiliAnchorProgram = {};\n";
  }

  const banner = "// Auto-generated by packages/sdk/src/generate.ts\n";
  await fs.writeFile(outputTypesPath, banner + typeSource, "utf8");
  await fs.writeFile(outputIndexPath, `${banner}export * from "./lili_anchor_program";\n`, "utf8");
}

ensureGeneratedFiles()
  .then(() => {
    console.log("SDK generated at", outputDir);
  })
  .catch((error) => {
    console.error("Failed to generate SDK", error);
    process.exitCode = 1;
  });
